### ISSUE TITLE
what is --image_pairs_txt  ?

### ISSUE THREAD

**Issue by JohnsonXi** [Jerome-Young/D4-VTON#2]
What is the meaning of  --image_pairs_txt <test_pairs_unpaired_1018.txt|test_pairs_paired_1018.txt> \？, i cant find this txt in VITONHD dataset.

**Comment by Jerome-Young** [comment]
> What is the meaning of --image_pairs_txt <test_pairs_unpaired_1018.txt|test_pairs_paired_1018.txt> \？, i cant find this txt in VITONHD dataset.

I used the 512x384 resolution dataset provided by [GP-VTON](https://github.com/xiezhy6/GP-VTON) for training and testing. The file `test_pairs_unpaired_1018.txt` in this dataset is similar to the `test_pairs.txt` provided in the original VITONHD dataset.

**Comment by JohnsonXi** [comment]
i download VITONHD dataset in this [https://pan.baidu.com/s/1tsoaYPnevI-EsqxYZZyIbg?pwd=f9sc].
but dont find txt in here, and all images are black. Could you provide this dataset on google drive? thanks.
<img width="951" alt="image" src="https://github.com/user-attachments/assets/e8530ec2-db5b-49c2-89b7-f8eae670ace8">

**Comment by Jerome-Young** [comment]
> i download VITONHD dataset in this [https://pan.baidu.com/s/1tsoaYPnevI-EsqxYZZyIbg?pwd=f9sc]. but dont find txt in here, and all images are black. Could you provide this dataset on google drive? thanks.

Download from [VITONHD](https://pan.baidu.com/s/16oJAl_VS18gQ2XHHhKgliA?pwd=e985), the folder structure should look like this:
```
|── VITON-HD-512
|   |── test_pairs_paired_1018.txt
|   |──test_pairs_unpaired_1018.txt
|   |── train_pairs_1018.txt
|   |── [train | test]
|   |   |── image
|   |   |── cloth
|   |   |── cloth_mask-bytedance
|   |   |── cloth_parse-bytedance
|   |   |── densepose
|   |   |── openpose_img
|   |   |── openpose_json
|   |   |── parse-bytedance
```
