### ISSUE TITLE
Problem of reproducing results

### ISSUE THREAD

**Issue by Baicheng42** [Jerome-Young/D4-VTON#3]
Hi, thanks for your great work!

I followed your readme to download the weights and reproduced the results, the deformation(warping) results are very good, but the results of the synthesis stage are poor.

1. the visualization results. Some textures are poorly restored. This phenomenon occurs on most images.
![d4vton_1](https://github.com/user-attachments/assets/796521be-1514-4862-8142-112f0ca4e7bb)
![d4vton_2](https://github.com/user-attachments/assets/1618fbe8-f43d-4afb-a4e4-eb05d1a9cbd6)

2. the FID results are poor. I obtained a paired/unpaired FID of 9.10/12.51, while the D4-VTON paper reports 4.85/8.53.
![3](https://github.com/user-attachments/assets/37b86fea-3c50-48cd-96cb-d944c9fab2d7)
![4](https://github.com/user-attachments/assets/ca43d044-5e47-4079-b56d-8b72c65ae979)

My command of testing results is
`fidelity --gpu 0  --fid 
    --input1 /home/work/xxxx/D4-VTON/Synthesis_Stage/results/d4vton_paired_syn/result/ 
    --input2 /home/work/xxxx/data/VITON-HD-512/gt/image_512/
`

Could you please check the ckpt or tell me how to fix it?

Thank you!

**Comment by Jerome-Young** [comment]
> Hi, thanks for your great work!
> 
> I followed your readme to download the weights and reproduced the results, the deformation(warping) results are very good, but the results of the synthesis stage are poor.
> 
> 1. the visualization results. Some textures are poorly restored. This phenomenon occurs on most images.
>    ![d4vton_1](https://private-user-images.githubusercontent.com/53386314/365966719-796521be-1514-4862-8142-112f0ca4e7bb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MzA1NjEsIm5iZiI6MTcyNjYzMDI2MSwicGF0aCI6Ii81MzM4NjMxNC8zNjU5NjY3MTktNzk2NTIxYmUtMTUxNC00ODYyLTgxNDItMTEyZjBjYTRlN2JiLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAzMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMjM1YTJkZTZhMGI1YjczZWYzNTQwZjFiZTE5YTgzNDAwMzM3MzhlMDM0NWUzNzhmYzFhYjNmOGY1OWRkMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.UmU06TEFMYsIsWnyLjqvvTyISowMt7pD7HZdvEqbXpU)
>    ![d4vton_2](https://private-user-images.githubusercontent.com/53386314/365966790-1618fbe8-f43d-4afb-a4e4-eb05d1a9cbd6.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MzA1NjEsIm5iZiI6MTcyNjYzMDI2MSwicGF0aCI6Ii81MzM4NjMxNC8zNjU5NjY3OTAtMTYxOGZiZTgtZjQzZC00YWZiLWE0ZTQtZWIwNWQxYTljYmQ2LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAzMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMTc0ODE4Y2U5ODliYzhkYTcwMjU4ZjUwNzdiMmY4NDFlZTk0NjhmMzhiMjZlNDdhMzMwYTYwZGI4ZTcyMzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AcusGsVaiXhU9gNyvEn6-K74HKuk65AMH0MUoraOcfM)
> 2. the FID results are poor. I obtained a paired/unpaired FID of 9.10/12.51, while the D4-VTON paper reports 4.85/8.53.
>    ![3](https://private-user-images.githubusercontent.com/53386314/365969112-37b86fea-3c50-48cd-96cb-d944c9fab2d7.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MzA1NjEsIm5iZiI6MTcyNjYzMDI2MSwicGF0aCI6Ii81MzM4NjMxNC8zNjU5NjkxMTItMzdiODZmZWEtM2M1MC00OGNkLTk2Y2ItZDk0NGM5ZmFiMmQ3LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAzMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5MmNkNmQyM2FiMWRmYmIwMzNjOGM4ZmY1NWQ5YTY2ZDRhNDkzMTNhMmQyYjg0NDY2OWVkMzJkYWM2ODQ0NjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pa5CsIURjhjU1hreCojEcgGx8434tmSkTNJOoR-Ku3E)
>    ![4](https://private-user-images.githubusercontent.com/53386314/365969136-ca43d044-5e47-4079-b56d-8b72c65ae979.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MzA1NjEsIm5iZiI6MTcyNjYzMDI2MSwicGF0aCI6Ii81MzM4NjMxNC8zNjU5NjkxMzYtY2E0M2QwNDQtNWU0Ny00MDc5LWI1NmQtOGI3MmM2NWFlOTc5LmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE4VDAzMzEwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAwODNkNDY3MTIwMjA3ZTAyNmIyNDJmMGUwMDhmZmM2ZTE3NjBkNTgzOTg2ZTg1NjdjNjc4Mzg1NjAzNGFlNWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7S142pL7mGYJ3dbFZ3eiYHlxBFKY5OT2Ni_8ehWOB2w)
> 
> My command of testing results is `fidelity --gpu 0 --fid --input1 /home/work/xxxx/D4-VTON/Synthesis_Stage/results/d4vton_paired_syn/result/ --input2 /home/work/xxxx/data/VITON-HD-512/gt/image_512/ `
> 
> Could you please check the ckpt or tell me how to fix it?
> 
> Thank you!

Thanks for your interest in our work.
1. Our method may underperform when handling some little writing. You can try fine-tuning the VAE encoder/decoder on the VITON-HD dataset to alleviate this issue.
2. Different downsampling methods can potentially lead to significant variations in the evaluation metrics. How did you obtain the 512 resolution ground truth images? The metrics reported in the paper were directly calculated using the output and the filtered test folder in [here](https://pan.baidu.com/share/init?surl=6oJAl_VS18gQ2XHHhKgliA&pwd=e985).

**Comment by Baicheng42** [comment]
Thank you!! your work is **excellent and reproducible** after testing as you say.

The confusion I still have is that the test data I used earlier was from resized HR-VITON followed by the [CVPR24 tpd](https://github.com/Gal4way/TPD/blob/main/utils/generate_GT.py). The metrics of this data are very different from the those of your data. Have you ever noticed this phenomenon? Did you follow DCI-VTON or other mainstream methods to prepare your data?

Thank you again for your outstanding work and for taking the time to address my concerns.

**Comment by Jerome-Young** [comment]
> Thank you!! your work is **excellent and reproducible** after testing as you say.
> 
> The confusion I still have is that the test data I used earlier was from resized HR-VITON followed by the [CVPR24 tpd](https://github.com/Gal4way/TPD/blob/main/utils/generate_GT.py). The metrics of this data are very different from the those of your data. Have you ever noticed this phenomenon? Did you follow DCI-VTON or other mainstream methods to prepare your data?
> 
> Thank you again for your outstanding work and for taking the time to address my concerns.

This depends on the data used for supervision during training. You can fine-tune the model using the prepared data at your disposal.
