### ISSUE TITLE
Please contact me 

### ISSUE THREAD

**Issue by Asfiiiy** [Jerome-Young/D4-VTON#4]
My name is Asfand Yar i am making a project i am on cpu training your repo i am seeing a several of issues i almost done everything please contact me or eamil me yara67575@gmail.com to run this program i am making a web project i am facing this issues last month every time i managed one issue its come another i don't understand why please contact me 

File "D:\xamp\htdocs\project\Upload\D4-VTON\Synthesis_Stage\ldm\models\diffusion\ddim.py", line 186, in p_sample_ddim
    x = torch.cat([x, kwargs['inpaint_image'], kwargs['inpaint_mask']], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 32 for tensor number 1 in the list.

 return func(*args, **kwargs)
  File "D:\xamp\htdocs\project\Upload\D4-VTON\Synthesis_Stage\ldm\models\diffusion\ddim.py", line 175, in ddim_sampling
    outs = self.p_sample_ddim(img, cond, ts, delta_step=delta_step, index=index,
  File "C:\ProgramData\miniconda3\envs\myenv\lib\site-packages\torch\utils\_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "D:\xamp\htdocs\project\Upload\D4-VTON\Synthesis_Stage\ldm\models\diffusion\ddim.py", line 200, in p_sample_ddim
    inpaint_image = kwargs['inpaint_image']
KeyError: 'inpaint_image'

**Comment by Jerome-Young** [comment]
> My name is Asfand Yar i am making a project i am on cpu training your repo i am seeing a several of issues i almost done everything please contact me or eamil me [yara67575@gmail.com](mailto:yara67575@gmail.com) to run this program i am making a web project i am facing this issues last month every time i managed one issue its come another i don't understand why please contact me
> 
> File "D:\xamp\htdocs\project\Upload\D4-VTON\Synthesis_Stage\ldm\models\diffusion\ddim.py", line 186, in p_sample_ddim x = torch.cat([x, kwargs['inpaint_image'], kwargs['inpaint_mask']], dim=1) RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 32 for tensor number 1 in the list.
> 
> return func(*args, **kwargs) File "D:\xamp\htdocs\project\Upload\D4-VTON\Synthesis_Stage\ldm\models\diffusion\ddim.py", line 175, in ddim_sampling outs = self.p_sample_ddim(img, cond, ts, delta_step=delta_step, index=index, File "C:\ProgramData\miniconda3\envs\myenv\lib\site-packages\torch\utils_contextlib.py", line 116, in decorate_context return func(*args, **kwargs) File "D:\xamp\htdocs\project\Upload\D4-VTON\Synthesis_Stage\ldm\models\diffusion\ddim.py", line 200, in p_sample_ddim inpaint_image = kwargs['inpaint_image'] KeyError: 'inpaint_image'

Thanks for your interest in our work. I have tested the code only in a GPU environment and haven't had a chance to test it on a CPU yet. The errors you're encountering might be related to differences in the computation or resource management between CPU and GPU setups.

If possible, I recommend running the code on a machine with a GPU to see if the issue persists.
